site_name: Global Economy Equilibrium Scenario Builder

theme:
    name: material
    font: 
        code: "PT Mono"
        text: "Open Sans"
        # text: "Montserrat"
        # text: "Work Sans"
        # text: "Nunito"
        # text: "Rubik"
    icon: 
        # logo: octicons/globe-24
        # logo: fontawesome/solid/globe
        logo: fontawesome/solid/scale-balanced
        repo: fontawesome/brands/github
    favicon: "mkdocs/globe.ico"
    palette:
        scheme: default
    features:
        - navigation.tabs
        - navigation.indexes

repo_url: https://github.com/Global-Projection-Model-Network/GEES
repo_name: GEES on GitHub
edit_uri: ""

extra:
  version: 2022

use_directory_urls: false
docs_dir: ./docs-source
site_dir: ./docs

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.critic
    - pymdownx.highlight
    - pymdownx.superfences
    - footnotes
    - meta
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - pymdownx.snippets
    - md_in_html


extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
    - mkdocs/extra.css

plugins:
    - search
    - awesome-pages

